spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
spring.application.name=vlc

spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB


server.port=8080
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# Cloudinary Credentials
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# JWT Secret Key
jwt.secret=${JWT_SECRET}



